motor_1:
  alarm_pin: 247
  direction_pin: 255
  enable_pin: 255
  max_rpm: 3000.0
  pulse_pin: 250
  refresh_rate: 10

motor_2:
  alarm_pin: 248
  direction_pin: 255
  enable_pin: 255
  max_rpm: 3000.0
  pulse_pin: 251
  refresh_rate: 10

motor_3:
  alarm_pin: 249
  direction_pin: 255
  enable_pin: 255
  max_rpm: 3000.0
  pulse_pin: 252
  refresh_rate: 10
