encoder_1:
  counts_per_rev: 4096.0
  refresh_rate: 10
  ss_pin: 253

encoder_2:
  counts_per_rev: 4096.0
  refresh_rate: 10
  ss_pin: 254

encoder_3:
  counts_per_rev: 4096.0
  refresh_rate: 10
  ss_pin: 255
