encoder_1:
  counts_per_rev: 4000.0
  refresh_rate: 1
  ss_pin: 10 # wiringPi numbering system

encoder_2:
  counts_per_rev: 4000.0
  refresh_rate: 10
  ss_pin: 254 # wiringPi numbering system

encoder_3:
  counts_per_rev: 4000.0
  refresh_rate: 10
  ss_pin: 255 # wiringPi numbering system
