encoder_1:
  counts_per_rev: 4096.0
  input_radius: 0.01 # [m]
  refresh_rate: 50
  ss_pin: 3 # wiringPi numbering system

encoder_2:
  counts_per_rev: 4096.0
  input_radius: 0.01 # [m]
  refresh_rate: 10
  ss_pin: 254 # wiringPi numbering system

encoder_3:
  counts_per_rev: 4096.0
  input_radius: 0.01 # [m]
  refresh_rate: 10
  ss_pin: 255 # wiringPi numbering system
